@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.capability.maxhealth;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
