@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.crafting.ingredient;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
