@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.capability.lastusetime;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
