@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.inventory.itemhandler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
