@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.capability.fluidhandler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
