@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.inventory.itemhandler.wrapper;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
