package choonster.testmod3.world.level.storage.loot.predicates;

import com.mojang.serialization.MapCodec;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;

/**
 * A condition that makes a best-effort attempt to determine if the loot is being generated by a chest.
 *
 * @author Choonster
 */
public class IsChestLoot implements LootItemCondition {
	private static final IsChestLoot INSTANCE = new IsChestLoot();

	public static final MapCodec<IsChestLoot> CODEC = MapCodec.unit(INSTANCE);

	private IsChestLoot() {
	}

	@Override
	public MapCodec<? extends LootItemCondition> codec() {
		return CODEC;
	}

	@Override
	public boolean test(final LootContext lootContext) {
		// BlockEntityLockableLoot#fillWithLoot always provides the ORIGIN parameter, sometimes provides THIS_ENTITY and
		// never provides any other parameter.

		return lootContext.hasParameter(LootContextParams.ORIGIN) &&
				!lootContext.hasParameter(LootContextParams.DAMAGE_SOURCE) &&
				!lootContext.hasParameter(LootContextParams.ATTACKING_ENTITY) &&
				!lootContext.hasParameter(LootContextParams.DIRECT_ATTACKING_ENTITY) &&
				!lootContext.hasParameter(LootContextParams.BLOCK_STATE) &&
				!lootContext.hasParameter(LootContextParams.BLOCK_ENTITY) &&
				!lootContext.hasParameter(LootContextParams.TOOL) &&
				!lootContext.hasParameter(LootContextParams.EXPLOSION_RADIUS);
	}

	public static LootItemCondition.Builder builder() {
		return () -> INSTANCE;
	}
}
