@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.advancements.criterion;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
