@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.advancements.criterion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
