@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.capability.chunkenergy;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
