@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.testmod3.capability.chunkenergy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
